version: '3'

services:
  frontend:
    build: ./frontend
    container_name: react-ui
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - mern-network

  backend:
    build: ./backend
    container_name: node-api
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    depends_on:
      - database
    networks:
      - mern-network

  database:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - O:\FoodHub\mongo-backup:/data/db
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge
